export default () => ({
  DATABASE_URL_DELIVERIES: process.env.DATABASE_URL_DELIVERIES,
  RABBIT_MQ_URI: process.env.RABBIT_MQ_URI,
  RABBIT_MQ_DELIVERIES_QUEUE: process.env.RABBIT_MQ_DELIVERIES_QUEUE,
});
