version: '3'

services:
  client:
    container_name: client
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

  commercial:
    container_name: commercial
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: ./apps/commercial/Dockerfile
    restart: always
    ports:
      - 3001:3000
    networks:
      - app_network

  livreur:
    container_name: livreur
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: ./apps/livreur/Dockerfile
    restart: always
    ports:
      - 3002:3000
    networks:
      - app_network

  restaurateur:
    container_name: restaurateur
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: ./apps/restaurateur/Dockerfile
    restart: always
    ports:
      - 3003:3000
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
