export default () => ({
  DATABASE_URL_NOTIFICATIONS: process.env.DATABASE_URL_NOTIFICATIONS,
  RABBIT_MQ_URI: process.env.RABBIT_MQ_URI,
  RABBIT_MQ_NOTIFICATIONS_QUEUE: process.env.RABBIT_MQ_NOTIFICATIONS_QUEUE,
});
