import './globals.css';
import '@repo/ui/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Navbar } from '@repo/ui';
import Image from 'next/image';
import { HomeOutlined, RestaurantOutlined } from '@mui/icons-material';
import Logo from './favicon.ico';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

const items = [
  { icon: <HomeOutlined />, text: 'Accueil', id: '1', href: '/' },
  { icon: <RestaurantOutlined />, text: 'Gestion Restaurant', id: '2', href: '/restaurant' },
];

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-row w-screen h-screen overflow-hidden border-0 pb-12 md:pb-0`}
      >
        <Navbar
          items={items}
          logo={
            <Image
              alt="Logo"
              height={64}
              src={Logo}
              width={64}
            />
          }
        />
        <div className="flex-1 md:overflow-y-auto md:overflow-x-hidden flex justify-center items-center">
          {children}
        </div>
      </body>{' '}
    </html>
  );
}
