export enum Microservices {
  USERS = 'USERS',
  AUTH = 'AUTH',
  ORDERS = 'ORDERS',
  RESTAURANTS = 'RESTAURANTS',
  DELIVERIES = 'DELIVERIES',
  STATISTICS = 'STATISTICS',
  NOTIFICATIONS = 'NOTIFICATIONS',
}
