services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    command: pnpm run start:dev api-gateway
    env_file:
      - ./.docker.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq
    ports:
      - '7000:7000'
    networks:
      - api

  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
      target: development
    command: pnpm run start:dev auth-service
    env_file:
      - ./.docker.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq
    ports:
      - '7001:7001'
    networks:
      - api

  orders-service:
    build:
      context: .
      dockerfile: ./apps/orders-service/Dockerfile
      target: development
    command: pnpm run start:dev orders-service
    env_file:
      - ./.docker.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq
    networks:
      - api

  restaurants-service:
    build:
      context: .
      dockerfile: ./apps/restaurants-service/Dockerfile
      target: development
    command: pnpm run start:dev restaurants-service
    env_file:
      - ./.docker.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq
    networks:
      - api

  deliveries-service:
    build:
      context: .
      dockerfile: ./apps/deliveries-service/Dockerfile
      target: development
    command: pnpm run start:dev deliveries-service
    env_file:
      - ./.docker.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq
    networks:
      - api

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
    networks:
      - api

  postgre-users:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - '5434:5432'
    restart: unless-stopped
    networks:
      - api

networks:
  api:
    driver: bridge
